#%RAML 0.8
title: nevermore
baseUri: http://baserurl:5000/
version: v1.0
protocols: [ HTTP, HTTPS ]

/report:
  post:
    description: 保存实验报告(相同student_id、class_id和experiment_id的报告会覆盖，提交后的报告无法再保存）
    body:
      application/json:
        schema: |
          {
            "student_id"      :"1434323",
            "class_id"        :"5",
            "experiment_id"   :"1",
            "report"          :{

            }
          }
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "code":"200",
                "data":""
              }
  /{student_id}/{class_id}/{experiment_id}:
    get:
      description: 获取实验报告（对于已经提交的报告返回带评分）
      body:
        application/json:
          schema: |
            {}
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "code":"200",
                  "data":{
                  }
                }
    post:
      description: 提交报告并打分，返回带token的报告，token用于查询答案
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "code":"200",
                  "data":{
                    "token" : "6n2pStDSBrcIH6MNVjEVsFMK09D0Pgof",
                    "section_total_scores" : [0,0,20,20,20,20,20],
                    "total_score" : 100,
                    "section_scores" : [0,0,2,1,10,8,6],
                    "final_score" : 27,
                    "section_counts" : [0,0,30,11,8,16,6],
                    "section_correct_counts" : [0,0,2,3,1,2,3],
                    "example1":{
                      "type":"fill-in-the-blank",
                      "answer":10,
                      "score":1
                    },
                    "example2":{
                      "type":"choice",
                      "answer":"A",
                      "score":0
                    }
                  }
                }

  /template/{experiment_id}:
    get:
      description: 获取实验报告模板
      body:
        application/json:
          schema: |
            {}
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "code":"200",
                  "data":{}
                }

  /answer/{experiment_id}:
    get:
      description: 获取正确答案
      headers:
        token:
          description: 提交实验报告后获取的token
          type: string
      body:
        application/json:
          schema: |
            {}
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "code":"200",
                  "data":{
                    "example1":{
                      "type":"fill-in-the-blank",
                      "answer":10,
                      "range":0.3
                    },
                    "example2":{
                      "type":"choice",
                      "answer":"A"
                    }
                  }
                }

